
typedef struct {
	int bg_charge;
	int bg_discharge;
	int fg_charge;
	int fg_discharge;
} default_colors;

#define BGC 0 // dark green
#define BGD 1 // dark red
#define FGC 2 // white
#define FGD 3 // white

int d_colors[] = { 25, 31, 141, 141 };

const char * x_colors[] = {
	"alice blue",
	"antique white",
	"aqua",
	"aquamarine",
	"azure",
	"beige",
	"bisque",
	"black",
	"blanched almond",
	"blue",
	"blue violet",
	"brown",
	"burlywood",
	"cadet blue",
	"chartreuse",
	"chocolate",
	"coral",
	"cornflower",
	"cornsilk",
	"crimson",
	"cyan",
	"dark blue",
	"dark cyan",
	"dark goldenrod",
	"dark gray",
	"dark green",
	"dark khaki",
	"dark magenta",
	"dark olive green",
	"dark orange",
	"dark orchid",
	"dark red",
	"dark salmon",
	"dark sea green",
	"dark slate blue",
	"dark slate gray",
	"dark turquoise",
	"dark violet",
	"deep pink",
	"deep sky blue",
	"dim gray",
	"dodger blue",
	"firebrick",
	"floral white",
	"forest green",
	"fuchsia",
	"gainsboro",
	"ghost white",
	"gold",
	"goldenrod",
	"gray",
	"web gray",
	"green",
	"web green",
	"green yellow",
	"honeydew",
	"hot pink",
	"indian red",
	"indigo",
	"ivory",
	"khaki",
	"lavender",
	"lavender blush",
	"lawn green",
	"lemon chiffon",
	"light blue",
	"light coral",
	"light cyan",
	"light goldenrod",
	"light gray",
	"light green",
	"light pink",
	"light salmon",
	"light sea green",
	"light sky blue",
	"light slate gray",
	"light steel blue",
	"light yellow",
	"lime",
	"lime green",
	"linen",
	"magenta",
	"maroon",
	"web maroon",
	"medium aquamarine",
	"medium blue",
	"medium orchid",
	"medium purple",
	"medium sea green",
	"medium slate blue",
	"medium spring green",
	"medium turquoise",
	"medium violet red",
	"midnight blue",
	"mint cream",
	"misty rose",
	"moccasin",
	"navajo white",
	"navy blue",
	"old lace",
	"olive",
	"olive drab",
	"orange",
	"orange red",
	"orchid",
	"pale goldenrod",
	"pale green",
	"pale turquoise",
	"pale violet red",
	"papaya whip",
	"peach puff",
	"peru",
	"pink",
	"plum",
	"powder blue",
	"purple",
	"web purple",
	"rebecca purple",
	"red",
	"rosy brown",
	"royal blue",
	"saddle brown",
	"salmon",
	"sandy brown",
	"sea green",
	"seashell",
	"sienna",
	"silver",
	"sky blue",
	"slate blue",
	"slate gray",
	"snow",
	"spring green",
	"steel blue",
	"tan",
	"teal",
	"thistle",
	"tomato",
	"turquoise",
	"violet",
	"wheat",
	"white",
	"white smoke",
	"yellow",
	"yellow green"
};
